begin;
create temp table backend_audit_results(check_name text,passed boolean) on commit drop;
do $test$
declare
 original_role text:=current_user; lender uuid:=gen_random_uuid(); borrower uuid:=gen_random_uuid(); stranger uuid:=gen_random_uuid(); item uuid; request1 uuid; request2 uuid; transaction1 uuid; listing uuid; message1 uuid; failed boolean;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(lender,lender::text||'@backend-audit.invalid','{"full_name":"Audit lender"}'),(borrower,borrower::text||'@backend-audit.invalid','{"full_name":"Audit borrower"}'),(stranger,stranger::text||'@backend-audit.invalid','{"full_name":"Audit stranger"}');
 if (select count(*) from public.profiles where id in(lender,borrower,stranger))<>3 then raise exception 'Profile signup trigger failed';end if;
 perform set_config('request.jwt.claim.sub',lender::text,true);perform set_config('role','authenticated',true);
 insert into public.lending_items(owner_id,title,category,description,pickup_location,max_borrow_days,available_from) values(lender,'Backend audit book','Books','Temporary rollback-only test','Library',7,current_date) returning id into item;
 insert into public.lost_found_items(owner_id,listing_type,item_name,category,description,location,event_date) values(lender,'found','Backend audit item','Books','Temporary rollback-only test','Library',current_date) returning id into listing;
 update public.profiles set full_name='Audit lender updated' where id=lender;
 failed:=false;begin update public.profiles set role='admin' where id=lender;exception when insufficient_privilege then failed:=true;end;if not failed then raise exception 'Role escalation was allowed';end if;
 perform set_config('request.jwt.claim.sub',borrower::text,true);
 failed:=false;begin insert into public.borrow_requests(item_id,borrower_id,start_date,return_date,student_name,student_email) values(item,borrower,current_date,current_date+8,'Audit borrower','audit@invalid');exception when others then failed:=true;end;if not failed then raise exception 'Excessive borrowing duration was allowed';end if;
 insert into public.borrow_requests(item_id,borrower_id,start_date,return_date,student_name,student_email) values(item,borrower,current_date,current_date+1,'Audit borrower','audit@invalid') returning id into request1;
 failed:=false;begin insert into public.borrow_requests(item_id,borrower_id,start_date,return_date,student_name,student_email) values(item,borrower,current_date,current_date+1,'Audit borrower','audit@invalid');exception when unique_violation then failed:=true;end;if not failed then raise exception 'Duplicate pending request was allowed';end if;
 failed:=false;begin perform public.approve_borrow_request(request1);exception when others then failed:=true;end;if not failed then raise exception 'Borrower approved own request';end if;
 perform set_config('request.jwt.claim.sub',stranger::text,true);
 if exists(select 1 from public.borrow_requests where id=request1) then raise exception 'Stranger can read private request';end if;
 failed:=false;begin perform public.reject_borrow_request(request1);exception when others then failed:=true;end;if not failed then raise exception 'Stranger rejected another request';end if;
 perform set_config('request.jwt.claim.sub',lender::text,true);
 if not exists(select 1 from public.notifications where entity_id=request1 and type='borrow_request') then raise exception 'Borrow request notification missing';end if;
 perform public.reject_borrow_request(request1);
 perform set_config('request.jwt.claim.sub',borrower::text,true);
 insert into public.borrow_requests(item_id,borrower_id,start_date,return_date,student_name,student_email) values(item,borrower,current_date,current_date+1,'Audit borrower','audit@invalid') returning id into request2;
 perform set_config('request.jwt.claim.sub',lender::text,true);perform public.reject_borrow_request(request2);
 perform set_config('request.jwt.claim.sub',borrower::text,true);
 insert into public.borrow_requests(item_id,borrower_id,start_date,return_date,student_name,student_email) values(item,borrower,current_date,current_date+1,'Audit borrower','audit@invalid') returning id into request1;
 perform set_config('request.jwt.claim.sub',lender::text,true);perform public.approve_borrow_request(request1);
 select id into transaction1 from public.borrow_transactions where request_id=request1;
 if transaction1 is null then raise exception 'Approval did not create a loan';end if;
 failed:=false;begin update public.lending_items set status='archived' where id=item;exception when others then failed:=true;end;if not failed then raise exception 'Active loan was archived';end if;
 perform set_config('request.jwt.claim.sub',borrower::text,true);
 if not exists(select 1 from public.lending_items where id=item and status='borrowed') then raise exception 'Borrower cannot read borrowed listing';end if;
 perform public.create_due_reminders();perform public.create_due_reminders();
 if (select count(*) from public.notifications where entity_id=transaction1 and type='due_reminder')<>1 then raise exception 'Reminder deduplication failed';end if;
 perform public.request_item_return(transaction1);
 if not exists(select 1 from public.borrow_transactions where id=transaction1 and status='return_requested') then raise exception 'Return request failed';end if;
 failed:=false;begin perform public.confirm_item_return(transaction1);exception when others then failed:=true;end;if not failed then raise exception 'Borrower confirmed own return';end if;
 perform set_config('request.jwt.claim.sub',lender::text,true);perform public.confirm_item_return(transaction1);
 if not exists(select 1 from public.lending_items where id=item and status='available') then raise exception 'Confirmed return did not restore availability';end if;
 perform set_config('request.jwt.claim.sub',borrower::text,true);
 insert into public.borrow_requests(item_id,borrower_id,start_date,return_date,student_name,student_email) values(item,borrower,current_date,current_date+1,'Audit borrower','audit@invalid') returning id into request1;
 perform set_config('request.jwt.claim.sub',lender::text,true);perform public.approve_borrow_request(request1);
 select id into transaction1 from public.borrow_transactions where request_id=request1;
 perform set_config('request.jwt.claim.sub',borrower::text,true);perform public.request_item_return(transaction1);
 perform set_config('request.jwt.claim.sub',lender::text,true);perform public.owner_complete_loan(transaction1,true);
 if not exists(select 1 from public.lending_items where id=item and status='archived' and archived_at is not null) then raise exception 'Complete and archive failed';end if;
 perform set_config('request.jwt.claim.sub',borrower::text,true);
 insert into public.messages(listing_id,sender_id,recipient_id,body) values(listing,borrower,lender,'Rollback-only audit message') returning id into message1;
 perform set_config('request.jwt.claim.sub',lender::text,true);
 if not exists(select 1 from public.notifications where entity_id=listing and type='new_message') then raise exception 'Message notification missing';end if;
 update public.messages set read_at=now() where id=message1;
 failed:=false;begin update public.messages set body='Edited by recipient' where id=message1;exception when insufficient_privilege then failed:=true;end;if not failed then raise exception 'Recipient edited message content';end if;
 update public.lost_found_items set status='returned' where id=listing;
 perform set_config('request.jwt.claim.sub',borrower::text,true);
 if not exists(select 1 from public.lost_found_items where id=listing) then raise exception 'Closed conversation listing is inaccessible';end if;
 failed:=false;begin insert into public.messages(listing_id,sender_id,recipient_id,body) values(listing,borrower,stranger,'Should be denied');exception when others then failed:=true;end;if not failed then raise exception 'Conversation without listing owner was allowed';end if;
 perform set_config('request.jwt.claim.sub',stranger::text,true);
 if exists(select 1 from public.messages where id=message1) then raise exception 'Stranger read private messages';end if;
 perform set_config('request.jwt.claim.sub','',true);perform set_config('role','anon',true);
 failed:=false;begin perform public.confirm_item_return(transaction1);exception when insufficient_privilege then failed:=true;end;if not failed then raise exception 'Anonymous privileged RPC was allowed';end if;
 perform set_config('role',original_role,true);
 insert into backend_audit_results values('signup profile trigger',true),('listing create/edit',true),('profile role protection',true),('date and duration validation',true),('pending request uniqueness',true),('repeated rejection and repeat borrowing',true),('owner approval and borrower visibility',true),('notification triggers and deduplicated reminders',true),('two-step return and owner archive',true),('active loan protection',true),('message privacy and read-only receipt updates',true),('closed-listing conversation access',true),('anonymous RPC denial',true);
end;
$test$;
select * from backend_audit_results;
rollback;