begin;
create temp table storage_audit_results(check_name text,passed boolean) on commit drop;
do $test$
declare original_role text:=current_user; owner_user uuid:=gen_random_uuid(); borrower uuid:=gen_random_uuid(); stranger uuid:=gen_random_uuid(); item uuid; request1 uuid; id_path text; legacy_path text; photo_path text; message_path text; listing uuid;
begin
insert into auth.users(id,email,raw_user_meta_data) values(owner_user,owner_user::text||'@backend-audit.invalid','{"full_name":"Storage owner"}'),(borrower,borrower::text||'@backend-audit.invalid','{"full_name":"Storage borrower"}'),(stranger,stranger::text||'@backend-audit.invalid','{"full_name":"Storage stranger"}');
id_path:=borrower::text||'/'||gen_random_uuid()::text||'.jpg';
legacy_path:=borrower::text||'/id-cards/'||gen_random_uuid()::text||'.jpg';
photo_path:=owner_user::text||'/'||gen_random_uuid()::text||'.jpg';
insert into storage.objects(bucket_id,name,owner_id) values('student-id-cards',id_path,borrower::text),('item-images',legacy_path,borrower::text),('item-images',photo_path,owner_user::text);
perform set_config('request.jwt.claim.sub',owner_user::text,true);perform set_config('role','authenticated',true);
insert into public.lending_items(owner_id,title,category,description,pickup_location,available_from) values(owner_user,'Storage test item','Books','Rollback-only test','Library',current_date) returning id into item;
insert into public.lost_found_items(owner_id,listing_type,item_name,category,description,location,event_date) values(owner_user,'found','Storage test listing','Books','Rollback-only test','Library',current_date) returning id into listing;
perform set_config('request.jwt.claim.sub',borrower::text,true);
insert into public.borrow_requests(item_id,borrower_id,start_date,return_date,student_name,student_email,student_id_card_url) values(item,borrower,current_date,current_date+1,'Storage borrower','audit@invalid',id_path) returning id into request1;
if not exists(select 1 from storage.objects where bucket_id='student-id-cards' and name=id_path) then raise exception 'Borrower cannot read own ID';end if;
perform set_config('request.jwt.claim.sub',owner_user::text,true);
if not exists(select 1 from storage.objects where bucket_id='student-id-cards' and name=id_path) then raise exception 'Owner cannot review requested student ID';end if;
perform set_config('request.jwt.claim.sub',stranger::text,true);
if exists(select 1 from storage.objects where bucket_id='student-id-cards' and name=id_path) then raise exception 'Stranger can read student ID';end if;
if exists(select 1 from storage.objects where bucket_id='item-images' and name=legacy_path) then raise exception 'Stranger can read legacy ID';end if;
if not exists(select 1 from storage.objects where bucket_id='item-images' and name=photo_path) then raise exception 'Authenticated listing photo access broken';end if;
perform set_config('role',original_role,true);
update public.borrow_requests set student_id_card_url='https://qbiathghrwtmrlghkztd.supabase.co/storage/v1/object/public/item-images/'||legacy_path where id=request1;
perform set_config('request.jwt.claim.sub',owner_user::text,true);perform set_config('role','authenticated',true);
if not exists(select 1 from storage.objects where bucket_id='item-images' and name=legacy_path) then raise exception 'Owner cannot review legacy ID';end if;
insert into storage.objects(bucket_id,name,owner_id) values('avatars',owner_user::text||'/audit.jpg',owner_user::text);
perform set_config('request.jwt.claim.sub',borrower::text,true);
message_path:=borrower::text||'/'||owner_user::text||'/'||listing::text||'/'||gen_random_uuid()::text;
insert into storage.objects(bucket_id,name,owner_id) values('message-attachments',message_path,borrower::text);
insert into public.messages(listing_id,sender_id,recipient_id,body,attachment_path,attachment_type) values(listing,borrower,owner_user,'Storage audit attachment',message_path,'photo');
perform set_config('request.jwt.claim.sub',owner_user::text,true);
if not exists(select 1 from storage.objects where bucket_id='message-attachments' and name=message_path) then raise exception 'Recipient cannot read message media';end if;
perform set_config('request.jwt.claim.sub',stranger::text,true);
if exists(select 1 from storage.objects where bucket_id='message-attachments' and name=message_path) then raise exception 'Stranger can read message media';end if;
perform set_config('request.jwt.claim.sub','',true);perform set_config('role','anon',true);
if exists(select 1 from storage.objects where bucket_id in ('item-images','student-id-cards','message-attachments')) then raise exception 'Anonymous private storage visibility';end if;
perform set_config('role',original_role,true);
if exists(select 1 from storage.buckets where id in ('item-images','student-id-cards','message-attachments') and public) then raise exception 'Private bucket is public';end if;
insert into storage_audit_results values('private bucket configuration',true),('borrower and lender ID access',true),('legacy ID owner access and outsider denial',true),('authenticated listing photo access',true),('avatar owner upload',true),('message media sender/recipient access',true),('anonymous private storage denial',true);
end;$test$;
select * from storage_audit_results;
rollback;