import {supabase} from '../lib/supabase';
async function currentUserId(){const user=(await supabase!.auth.getUser()).data.user;if(!user)throw new Error('Please sign in again.');return user.id;}
export async function getMyRequests(){if(!supabase)return [];const userId=await currentUserId();const{data,error}=await supabase.from('borrow_requests').select('*, lending_items(id,title,image_urls,pickup_location,status,owner_id)').eq('borrower_id',userId).order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function getMyBorrowing(){if(!supabase)return [];const userId=await currentUserId();const{data,error}=await supabase.from('borrow_transactions').select('*, lending_items(id,title,image_urls,pickup_location,status)').eq('borrower_id',userId).order('created_at',{ascending:false});if(!error&&data?.length)return data.filter((transaction:any)=>['scheduled','active'].includes(transaction.status));const{data:approved,error:requestError}=await supabase.from('borrow_requests').select('id,item_id,start_date,return_date,status,lending_items(id,title,image_urls,pickup_location,status)').eq('borrower_id',userId).eq('status','approved').order('created_at',{ascending:false});if(requestError){if(error)throw error;throw requestError;}return(approved??[]).filter((request:any)=>request.lending_items?.status!=='return_pending').map((request:any)=>({id:`request-${request.id}`,request_id:request.id,item_id:request.item_id,borrower_id:userId,start_date:request.start_date,due_date:request.return_date,status:'active',lending_items:request.lending_items,request_only:true}));}
export async function getMyLending(){if(!supabase)return [];const userId=await currentUserId();const{data,error}=await supabase.from('lending_items').select('*, borrow_requests(id,status,student_name,student_email,start_date,return_date), borrow_transactions(id,status,due_date,borrower_id,borrower:profiles!borrow_transactions_borrower_id_fkey(id,full_name,avatar_url,department,academic_year))').eq('owner_id',userId).order('created_at',{ascending:false});if(error)throw error;return(data??[]).filter((item:any)=>item.status!=='archived'||item.borrow_transactions?.some((transaction:any)=>!['returned','cancelled'].includes(transaction.status)));}
export async function getIncomingRequests(){if(!supabase)return [];const{data,error}=await supabase.from('borrow_requests').select('*, lending_items!inner(id,title,image_urls,pickup_location,owner_id)').eq('lending_items.owner_id',(await supabase.auth.getUser()).data.user?.id??'').order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function getDashboardCounts(){if(!supabase)return{pending:0,borrowed:0,lent:0,listings:0,incoming:0,unread:0};const[requests,borrowing,lending,incoming,notices]=await Promise.all([getMyRequests(),getMyBorrowing(),getMyLending(),getIncomingRequests(),supabase.from('notifications').select('id,read').eq('read',false)]);if(notices.error)throw notices.error;return{pending:requests.filter((x:any)=>x.status==='pending').length,borrowed:borrowing.length,lent:lending.filter((x:any)=>x.borrow_transactions?.some((transaction:any)=>!['returned','cancelled'].includes(transaction.status))||['borrowed','reserved','return_pending'].includes(x.status)).length,listings:lending.filter((x:any)=>x.status!=='archived').length,incoming:incoming.filter((x:any)=>x.status==='pending').length,unread:notices.data?.length??0};}
export async function requestReturn(transactionId:string){if(!supabase)throw new Error('Supabase is not configured.');const{error}=await supabase.rpc('request_item_return',{p_transaction_id:transactionId});if(error){if(/request_item_return|schema cache/i.test(error.message))throw new Error('Apply 009_return_workflow.sql in Supabase to enable returns.');throw error;}}
export async function confirmReturn(transactionId:string){if(!supabase)throw new Error('Supabase is not configured.');const{error}=await supabase.rpc('confirm_item_return',{p_transaction_id:transactionId});if(error){if(/confirm_item_return|schema cache/i.test(error.message))throw new Error('Apply 009_return_workflow.sql in Supabase to confirm returns.');throw error;}}
export async function ownerCompleteLoan({transactionId,archive}:{transactionId:string;archive:boolean}){if(!supabase)throw new Error('Supabase is not configured.');const{error}=await supabase.rpc('owner_complete_loan',{p_transaction_id:transactionId,p_archive:archive});if(error){if(/owner_complete_loan|schema cache/i.test(error.message))throw new Error('Apply 009_return_workflow.sql in Supabase to complete this loan.');throw error;}}
