import * as auth from '../services/auth';
import {Eye,EyeOff} from 'lucide-react';
import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useAuth} from '../features/auth/AuthContext';

export function AuthPage({mode}:{mode:'login'|'signup'}){
  const nav=useNavigate();const{user}=useAuth();const[f,setF]=useState({name:'',email:'',password:''});const[showPassword,setShowPassword]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);
  if(user)return <Link to="/">Continue to your dashboard</Link>;
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(mode==='login')await auth.signIn(f.email,f.password);else {const result=await auth.signUp(f.email,f.password,f.name);if(!result.session){setMessage('Check your email to confirm your account, then sign in.');return;}}nav('/')}catch(e){setError(e instanceof Error?e.message:'Something went wrong.')}finally{setBusy(false)}}
  return <div className="auth"><Link className="brand" to="/"><span>FL</span> FindLoop</Link><form className="auth-card" onSubmit={submit}><p className="eyebrow">WELCOME {mode==='login'?'BACK':'IN'}</p><h1>{mode==='login'?'Your campus community awaits.':'Create your campus account.'}</h1><p>Use your campus email to keep exchanges trusted.</p>{mode==='signup'&&<label className="field"><span>Full name</span><input required autoComplete="name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label>}<label className="field"><span>Email address</span><input type="email" required autoComplete="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label className="field"><span>Password</span><span className="password-control"><input type={showPassword?'text':'password'} minLength={6} required autoComplete={mode==='login'?'current-password':'new-password'} value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><button className="password-toggle" type="button" aria-label={showPassword?'Hide password':'Show password'} title={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label>{error&&<p className="form-error">{error}</p>}{message&&<p className="success" role="status">{message}</p>}<button className="button submit" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button>{mode==='login'?<p><Link to="/forgot-password">Forgot your password?</Link> · New here? <Link to="/signup">Create an account</Link></p>:<p>Already a member? <Link to="/login">Sign in</Link></p>}<Link className="apk-auth-link" to="/download">Install FindLoop</Link></form></div>;
}

export function ForgotPassword(){const[email,setEmail]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function send(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await auth.resetPassword(email);setMessage('If that account exists, a reset link has been sent.')}catch(e){setError(e instanceof Error?e.message:'Could not send reset email.')}finally{setBusy(false)}}return <div className="auth"><Link className="brand" to="/">FindLoop</Link><form className="auth-card" onSubmit={send}><h1>Reset your password</h1><p>Enter your email and we’ll send a reset link.</p><label className="field"><span>Email address</span><input required value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label>{error&&<p className="form-error">{error}</p>}{message&&<p className="success">{message}</p>}<button disabled={busy} className="button submit">{busy?'Sending…':'Send reset link'}</button><Link to="/login">Back to sign in</Link></form></div>}

export function ResetPassword(){
 const{user,loading}=useAuth();const[password,setPassword]=useState('');const[confirmation,setConfirmation]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[saved,setSaved]=useState(false);
 async function submit(event:React.FormEvent){event.preventDefault();setError('');if(password!==confirmation){setError('Passwords do not match.');return;}setBusy(true);try{await auth.updatePassword(password);setSaved(true);}catch(error){setError(error instanceof Error?error.message:'Could not update your password.');}finally{setBusy(false);}}
 return <div className="auth"><Link className="brand" to="/">FindLoop</Link><form className="auth-card" onSubmit={submit}><h1>Choose a new password</h1>{loading?<p>Checking your reset link…</p>:!user?<p>Your reset link is missing or expired. <Link to="/forgot-password">Request a new link</Link>.</p>:saved?<p className="success">Your password was updated. <Link to="/">Continue to your account</Link>.</p>:<><label className="field"><span>New password</span><input type="password" minLength={6} autoComplete="new-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field"><span>Confirm password</span><input type="password" minLength={6} autoComplete="new-password" required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button submit" disabled={busy}>{busy?'Saving…':'Update password'}</button></>}</form></div>;
}
