import {Bell,BookOpenCheck,Check,ChevronLeft,Clock3,MessageCircle,PackageCheck,RotateCcw,X} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {Link,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {Empty,LoadingCards,PageIntro} from '../components/ui';
import {MessageComposer,MessageMedia} from '../components/MessageComposer';
import {useApproveRequest,useRejectRequest,useThread} from '../hooks/useInteractions';
import {useInbox,useMarkConversationRead,useMyBorrowing,useMyLending,useMyRequests,useNotifications,useOwnerRequests,useReadAllNotifications,useReadNotification,useReturnActions} from '../hooks/useWorkspace';
import {useAuth} from '../features/auth/AuthContext';

const date=(value:string)=>new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(value));
function Status({value}:{value:string}){return <span className={`status status-${value}`}>{value.replaceAll('_',' ')}</span>}
function ItemThumb({src}:{src?:string}){return <div className="row-thumb">{src?<img src={src} alt=""/>:<BookOpenCheck/>}</div>}

function ClickableRow({to,children,className='workspace-row'}:{to:string;children:React.ReactNode;className?:string}){
  const navigate=useNavigate();
  return <article className={`${className} clickable-row`} role="link" tabIndex={0} onClick={()=>navigate(to)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();navigate(to)}}}>{children}</article>;
}

export function MyRequests({embedded=false}:{embedded?:boolean}){
  const{data=[],isLoading,error}=useMyRequests();
  return <>{!embedded&&<PageIntro title="My requests" description="Every request you have sent, from pending review to completion."/>}{isLoading?<LoadingCards/>:error?<Empty title="Could not load requests" copy="Refresh the page and try again."/>:data.length?<div className="workspace-list">{data.map((request:any)=><ClickableRow to={`/app/borrow/${request.item_id}`} key={request.id}><ItemThumb src={request.lending_items?.image_urls?.[0]}/><div className="row-main"><div><h3>{request.lending_items?.title||'Borrow request'}</h3><Status value={request.status}/></div><p>{date(request.start_date)} – {date(request.return_date)}</p><small>{request.message}</small></div><span className="row-arrow">View →</span></ClickableRow>)}</div>:<Empty title="No requests sent" copy="Browse available items and send your first borrowing request." action={{to:'/app/borrow',label:'Browse items'}}/>}</>;
}

export function Borrowing(){
  const{data=[],isLoading}=useMyBorrowing();const actions=useReturnActions();
  return <><PageIntro title="Borrowed by me" description="Track active loans, deadlines, and returns."/>{isLoading?<LoadingCards/>:data.length?<div className="workspace-list">{data.map((transaction:any)=>{const overdue=!['returned','cancelled'].includes(transaction.status)&&new Date(transaction.due_date)<new Date();return <ClickableRow to={`/app/borrow/${transaction.item_id}`} key={transaction.id}><ItemThumb src={transaction.lending_items?.image_urls?.[0]}/><div className="row-main"><div><h3>{transaction.lending_items?.title||'Approved borrowing'}</h3><Status value={overdue?'overdue':transaction.status}/></div><p><Clock3 size={15}/> Due {date(transaction.due_date)}</p><small>{transaction.lending_items?.pickup_location?`Pickup: ${transaction.lending_items.pickup_location}`:transaction.request_only?'Approved · transaction access needs the latest database policy':'Campus lending item'}</small></div>{!transaction.request_only&&['scheduled','active'].includes(transaction.status)?<button className="button secondary" onClick={event=>{event.stopPropagation();actions.request.mutate(transaction.id)}}><RotateCcw size={16}/> Request return</button>:<span className="row-arrow">Details →</span>}</ClickableRow>})}</div>:<Empty title="Nothing borrowed" copy="Your approved loans and return deadlines will appear here." action={{to:'/app/borrow',label:'Explore lending'}}/>}</>;
}

export function Lending(){
  const{data=[],isLoading}=useMyLending();const actions=useReturnActions();const[filter,setFilter]=useState<'all'|'available'|'borrowed'>('all');
  const filtered=data.filter((item:any)=>{const onLoan=item.borrow_transactions?.some((transaction:any)=>!['returned','cancelled'].includes(transaction.status))||['borrowed','reserved','return_pending'].includes(item.status);return filter==='all'||(filter==='available'&&item.status==='available')||(filter==='borrowed'&&onLoan)});
  return <><PageIntro title="My lending" description="Manage available items and active loans." action={{to:'/app/borrow/new',label:'Add item'}}/><div className="lending-filters segmented" aria-label="Filter lending items">{(['all','available','borrowed'] as const).map(value=><button key={value} type="button" className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value}</button>)}</div>{isLoading?<LoadingCards/>:filtered.length?<div className="workspace-list">{filtered.map((item:any)=>{const active=item.borrow_transactions?.find((transaction:any)=>!['returned','cancelled'].includes(transaction.status));const returning=active?.status==='return_requested'?active:undefined;return <ClickableRow to={`/app/lending/${item.id}`} key={item.id}><ItemThumb src={item.image_urls?.[0]}/><div className="row-main"><div><h3>{item.title}</h3><Status value={returning?'return_requested':active?'borrowed':item.status}/></div><p>{item.library_name||'Personal collection'} · {item.pickup_location}</p>{returning?<small>{returning.borrower?.full_name||'The borrower'} reported this item returned · Confirm after receiving it</small>:active?<small>Borrowed by {active.borrower?.full_name||'Campus member'} · Due {date(active.due_date)}</small>:<small>{item.borrow_requests?.filter((request:any)=>request.status==='pending').length||0} pending requests</small>}</div>{returning?<button className="button" onClick={event=>{event.stopPropagation();actions.confirm.mutate(returning.id)}}><PackageCheck size={16}/> Confirm return</button>:<span className="row-arrow">Details →</span>}</ClickableRow>})}</div>:<Empty title={data.length?'No items in this filter':'No lending items'} copy={data.length?'Choose another filter to see your listings.':'Add books, equipment, or useful campus items.'} action={data.length?undefined:{to:'/app/borrow/new',label:'Add your first item'}}/>}</>;
}

export function RequestInbox({embedded=false}:{embedded?:boolean}){
  const{data=[],isLoading}=useOwnerRequests();const approve=useApproveRequest();const reject=useRejectRequest();
  const pending=data.filter((request:any)=>request.status==='pending');
  const content=isLoading?<LoadingCards/>:pending.length?<div className="workspace-list request-grid">{pending.map((request:any)=><article className="request-review" key={request.id}><div className="request-heading"><div><span className="tag">{request.lending_items?.title}</span><h3>{request.student_name||'Campus student'}</h3><p>{request.student_email}</p></div><Status value={request.status}/></div><div className="request-meta"><span><Clock3/> {date(request.start_date)} – {date(request.return_date)}</span><p>{request.message}</p>{request.student_id_card_url&&<a className="id-card-link" href={request.student_id_card_url} target="_blank" rel="noreferrer"><img src={request.student_id_card_url} alt={`${request.student_name||'Student'} ID card`}/><b>Open student ID</b></a>}</div><div className="request-actions"><button className="button secondary" disabled={reject.isPending||approve.isPending} onClick={()=>reject.mutate(request.id)}><X size={17}/> {reject.isPending?'Rejecting…':'Reject'}</button><button className="button approve-button" disabled={approve.isPending||reject.isPending} onClick={()=>approve.mutate(request.id)}><Check size={17}/> {approve.isPending?'Approving…':'Approve request'}</button></div>{(approve.error||reject.error)&&<p className="form-error" role="alert">{(approve.error||reject.error)?.message}</p>}</article>)}</div>:<Empty title="No incoming requests" copy="There are no requests waiting for your review."/>;
  return <>{!embedded&&<PageIntro title="Incoming requests" description="Review student verification and decide who can borrow your items."/>}{content}</>;
}

export function MessagesPage(){
  const{data=[],isLoading}=useInbox();
  return <><PageIntro title="Messages" description="Private conversations between item owners and finders."/>{isLoading?<LoadingCards/>:data.length?<div className="conversation-list">{data.map(conversation=><Link className="conversation-row" to={`/app/messages/${conversation.listingId}/${conversation.peerId}`} key={`${conversation.listingId}:${conversation.peerId}`}><div className="conversation-avatar">{conversation.listingImage?<img src={conversation.listingImage} alt=""/>:<MessageCircle/>}</div><div className="conversation-copy"><div><h3>{conversation.peerName}</h3><time>{new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(conversation.lastMessageAt))}</time></div><small>{conversation.listingTitle}</small><p>{conversation.lastMessage}</p></div>{conversation.unread>0&&<b className="unread-badge">{conversation.unread}</b>}</Link>)}</div>:<Empty title="No conversations" copy="Open a found listing and contact the finder to start a conversation." action={{to:'/app/lost-found?type=found',label:'Browse found items'}}/>}</>;
}

export function MessageThread(){
  const{listingId='',peerId=''}=useParams();const{user}=useAuth();const{data:conversations=[]}=useInbox();const conversation=conversations.find(item=>item.listingId===listingId&&item.peerId===peerId);const{data:messages=[],isLoading}=useThread(listingId,peerId);const read=useMarkConversationRead();const endRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(listingId&&peerId)read.mutate({listingId,peerId});return undefined},[listingId,peerId,messages.length]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'});return undefined},[messages.length]);
  return <section className="thread-page"><div className="thread-header"><Link to="/app/messages" aria-label="Back to messages"><ChevronLeft/></Link><div className="thread-person"><span>{conversation?.peerName?.[0]?.toUpperCase()||'U'}</span><div><h2>{conversation?.peerName||'Campus member'}</h2><p>{conversation?.listingTitle||'Item conversation'}</p></div></div><Link className="text-link" to={`/app/lost-found/${listingId}`}>View item</Link></div><div className="thread-body">{isLoading?<LoadingCards/>:messages.length?messages.map((message,index)=>{const mine=message.sender_id===user?.id;const showDate=index===0||new Date(messages[index-1].created_at).toDateString()!==new Date(message.created_at).toDateString();return <div key={message.id}>{showDate&&<div className="message-date">{date(message.created_at)}</div>}<div className={`bubble-row ${mine?'mine':''}`}><div className="message-bubble"><MessageMedia message={message}/><p>{message.body}</p><time>{new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(message.created_at))}</time></div></div></div>}):<div className="thread-empty"><MessageCircle/><p>Start the conversation about this item.</p></div>}<div ref={endRef}/></div><MessageComposer key={`${listingId}:${peerId}`} listingId={listingId} peerId={peerId}/></section>;
}

export function NotificationsPage(){
  const[params,setParams]=useSearchParams();const requestedTab=params.get('tab');const tab=requestedTab==='requests'||requestedTab==='my-requests'?requestedTab:'updates';
  const{data=[],isLoading}=useNotifications();const read=useReadNotification();const all=useReadAllNotifications();
  return <><PageIntro title="Notifications" description="Review your requests, incoming requests, approvals, messages, deadlines, and returns."/><div className="notification-tabs segmented"><button className={tab==='my-requests'?'active':''} onClick={()=>setParams({tab:'my-requests'})}>My requests</button><button className={tab==='requests'?'active':''} onClick={()=>setParams({tab:'requests'})}>Incoming</button><button className={tab==='updates'?'active':''} onClick={()=>setParams({tab:'updates'})}>Updates</button></div>{tab==='my-requests'?<MyRequests embedded/>:tab==='requests'?<RequestInbox embedded/>:<>{data.some(notice=>!notice.read)&&<div className="notification-tools"><span className="inapp-status"><Bell size={15}/> Live in-app alerts</span><button className="text-button" onClick={()=>all.mutate()}>Mark all read</button></div>}{isLoading?<LoadingCards/>:data.length?<div className="notification-list">{data.map(notice=><button key={notice.id} className={`notification-item ${notice.read?'':'unread'}`} onClick={()=>read.mutate(notice.id)}><span className="notification-icon">{notice.type.includes('message')?<MessageCircle/>:notice.type.includes('return')||notice.type.includes('due')||notice.type.includes('overdue')?<PackageCheck/>:<Bell/>}</span><span><b>{notice.title}</b><p>{notice.message}</p><small>{date(notice.created_at)}</small></span></button>)}</div>:<Empty title="You're all caught up" copy="Updates from every borrowing, lending, and messaging action will appear here."/>}</>}</>;
}
